AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchgateway:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: sample.lambda_handler
      Runtime: python3.12
      CodeUri:  s3://artifactoutbucket/sample.zip
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::637423317527:role/multirolelamda'
      Layers:
        - 'arn:aws:lambda:us-east-1:637423317527:layer:testlayer:6'
